---

- name: init deploy service
  hosts: deploy
  become: yes

  roles:
    - default
    - java_project

- name: init prod service
  hosts: prod
  become: yes

  roles:
    - webserver
    - deploy

